#pygments: true
highlighter: true
exclude: [README.md]

url: http://www.it3.be
career_email: info@it3.be
engineer_email: gratien.dhaese@it3.be

permalink: /:year/:month/:day/:title/

disqus_short_name: it3consultants

analytics_code: UA-3406473-1

share_twitter: true
share_google: true
share_facebook: false
share_reddit: false

# Put the authors in alphabetical order
authors:
  gratien:
    name: Gratien D'haese
    email: gratien.dhaese@it3.be
    position: Senior Consultant
    start_date: 1996-04-01
    github: gdha
    twitter: gratiendh
    linkedin: gratiendhaese
    gravatar: 79ba5ce1fe4f33cf89996260d80e77ec
    about: Besides IT3 Consultants, he is the author of several Open Source projects (see <a href="https://github.com/gdha" title="Github page of Gratien">GitHub page of Gratien Dhaese)</a>.
